name: tvaap_clean
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  just_audio: ^0.9.36
  country_flags: ^2.1.1
  wakelock_plus: ^1.2.0
  google_fonts: ^6.2.1
  webview_flutter: ^4.8.0
  html: ^0.15.4
  timezone: ^0.9.2
  flutter_local_notifications: ^17.2.2
  carousel_slider: ^5.0.0
  image: ^4.1.3
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  file_picker: ^8.1.7
  flutter_exif_rotation: ^0.5.1
  flutter_launcher_icons: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0


file_picker:
  git:
    url: https://github.com/miguelpruivo/flutter_file_picker.git
    ref: flutter3
  platforms:
    android:
      pluginClass: FilePickerPlugin
    ios:
      pluginClass: FilePickerPlugin
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/image/
    - assets/fonts/
    - assets/resim/
    - assets/resim/resim/
    - assets/resim/ramazan/
    - assets/resim/hadis/
    - assets/resim/dua/
    - assets/resim/namaz/
    - assets/resim/besmele/

  fonts:
    - family: Hasenat
      fonts:
        - asset: assets/fonts/hasenat.ttf
